-- Wine Price Tracker schema (PostgreSQL 15+)

-- One row per wine: one vintage of one product at one bottle size. Different vintages are
-- different wines; `family` groups the vintages of the same product.
CREATE TABLE IF NOT EXISTS wines (
    id             SERIAL PRIMARY KEY,
    slug           TEXT UNIQUE NOT NULL,
    family         TEXT NOT NULL,
    name           TEXT NOT NULL,
    vintage        TEXT NOT NULL,                  -- year, or 'NV' when none is printed
    region         TEXT,                           -- growing region parsed from the name (NULL if none)
    brand          TEXT,                           -- producer / brand parsed from the name
    grape          TEXT,                           -- grape variety, named or implied by the appellation
    classification TEXT,                           -- e.g. Grand Cru, Premier Cru, Reserva (NULL if none)
    size           TEXT NOT NULL,
    style          TEXT NOT NULL CHECK (style IN ('red', 'white', 'rose', 'sparkling', 'dessert')),
    tier           TEXT NOT NULL CHECK (tier IN ('everyday', 'premium', 'luxury')),
    source_codes   TEXT[] NOT NULL DEFAULT '{}',
    is_featured    BOOLEAN NOT NULL DEFAULT FALSE,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE   -- listed in the most recent price list
);

-- Growing regions with vineyard-centroid coordinates, for weather lookups.
CREATE TABLE IF NOT EXISTS regions (
    name       TEXT PRIMARY KEY,
    latitude   REAL NOT NULL,
    longitude  REAL NOT NULL,
    hemisphere TEXT NOT NULL CHECK (hemisphere IN ('N', 'S'))
);

-- One row per wine per price list. regular_price is the list price; promo_price is a
-- temporary sale ('sale', with dates) or a clearance markdown ('clearance').
CREATE TABLE IF NOT EXISTS price_observations (
    wine_id       INTEGER NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
    observed_on   DATE NOT NULL,
    source        TEXT NOT NULL,
    source_code   TEXT NOT NULL,
    vintage       TEXT,
    regular_price NUMERIC(10, 2) NOT NULL CHECK (regular_price > 0),
    promo_price   NUMERIC(10, 2),
    promo_type    TEXT CHECK (promo_type IN ('sale', 'clearance')),
    sale_start    DATE,
    sale_end      DATE,
    PRIMARY KEY (wine_id, observed_on, source)
);

CREATE TABLE IF NOT EXISTS model_runs (
    model_version TEXT PRIMARY KEY,
    trained_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    algorithm     TEXT NOT NULL,
    horizon       INTEGER NOT NULL,
    horizon_unit  TEXT NOT NULL,
    metrics       JSONB NOT NULL,
    artifact_uri  TEXT NOT NULL,   -- where the model.joblib lives: a local path or s3://...
    is_active     BOOLEAN NOT NULL DEFAULT FALSE
);

-- At most one active model at a time.
CREATE UNIQUE INDEX IF NOT EXISTS model_runs_one_active
    ON model_runs (is_active) WHERE is_active;

CREATE TABLE IF NOT EXISTS forecasts (
    model_version TEXT NOT NULL REFERENCES model_runs(model_version) ON DELETE CASCADE,
    wine_id       INTEGER NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
    target_date   DATE NOT NULL,
    p10           NUMERIC(10, 2) NOT NULL,
    p50           NUMERIC(10, 2) NOT NULL,
    p90           NUMERIC(10, 2) NOT NULL,
    p_up          REAL NOT NULL,    -- probability the list price is higher than today by target_date
    p_down        REAL NOT NULL,
    up_pct        REAL NOT NULL,    -- typical size of a rise / cut, in percent
    down_pct      REAL NOT NULL,
    PRIMARY KEY (model_version, wine_id, target_date)
);

-- Next-vintage outlook: how the following vintage of a currently listed vintage wine is likely
-- to be priced relative to it (from the next-vintage model).
CREATE TABLE IF NOT EXISTS vintage_outlook (
    model_version TEXT NOT NULL REFERENCES model_runs(model_version) ON DELETE CASCADE,
    wine_id       INTEGER NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
    next_vintage  INTEGER NOT NULL,
    p_up          REAL NOT NULL,
    p_down        REAL NOT NULL,
    p10_pct       REAL NOT NULL,
    p50_pct       REAL NOT NULL,
    p90_pct       REAL NOT NULL,
    PRIMARY KEY (model_version, wine_id)
);

-- Fair-price (hedonic) estimates for wines on the latest price list: what comparable wines cost,
-- from a model that never saw the wine or its other vintages. value_pct < 0 = priced below fair.
CREATE TABLE IF NOT EXISTS fair_prices (
    model_version TEXT NOT NULL REFERENCES model_runs(model_version) ON DELETE CASCADE,
    wine_id       INTEGER NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
    fair_p10      NUMERIC(10, 2) NOT NULL,
    fair_p50      NUMERIC(10, 2) NOT NULL,
    fair_p90      NUMERIC(10, 2) NOT NULL,
    value_pct     REAL NOT NULL,
    PRIMARY KEY (model_version, wine_id)
);

-- Plain-English explanations generated by Claude on Amazon Bedrock, cached per wine and model version.
CREATE TABLE IF NOT EXISTS explanations (
    model_version TEXT NOT NULL REFERENCES model_runs(model_version) ON DELETE CASCADE,
    wine_id       INTEGER NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
    text          TEXT NOT NULL,
    model_id      TEXT NOT NULL,
    input_tokens  INTEGER,
    output_tokens INTEGER,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (model_version, wine_id)
);

CREATE INDEX IF NOT EXISTS wines_name_lower ON wines (lower(name));
CREATE INDEX IF NOT EXISTS wines_family ON wines (family);
